#!/usr/bin/env bash
# Interactive local installer for clickup-agent.
#
# This script intentionally writes secrets only to a user config env file
# outside any workspace, with owner-only permissions. It does not send the
# token anywhere or commit it.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
DEFAULT_ENV_FILE="${HOME}/.config/clickup-agent/.env"
NON_INTERACTIVE="false"
YES="false"
API_KEY="${CLICKUP_API_KEY:-}"
WORKSPACE_ID="${CLICKUP_WORKSPACE_ID:-}"
WEBHOOK_SECRET="${CLICKUP_WEBHOOK_SECRET:-}"
INSTALL_METHOD="prompt"
CURSOR_SCOPE="prompt"
INSTALL_SKILL="false"

say() {
  printf '\n%s\n' "$*"
}

prompt_visible() {
  local prompt="$1"
  local default_value="${2:-}"
  local value

  if [[ -n "${default_value}" ]]; then
    read -r -p "${prompt} [${default_value}]: " value
    printf '%s' "${value:-$default_value}"
  else
    read -r -p "${prompt}: " value
    printf '%s' "${value}"
  fi
}

prompt_secret() {
  local prompt="$1"
  local required="${2:-false}"
  local value=""

  while true; do
    read -r -s -p "${prompt}: " value
    printf '\n' >&2
    if [[ -n "${value}" || "${required}" != "true" ]]; then
      printf '%s' "${value}"
      return 0
    fi
    printf 'This value is required.\n' >&2
  done
}

shell_quote_env_value() {
  local value="$1"
  value="${value//$'\r'/}"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '"%s"' "${value}"
}

usage() {
  cat <<'TXT'
Usage: bash scripts/install.sh [options]

Options:
  --non-interactive              Fail instead of prompting for missing required values.
  --api-key VALUE                ClickUp API token. Env fallback: CLICKUP_API_KEY.
  --workspace-id VALUE           Default workspace ID. Env fallback: CLICKUP_WORKSPACE_ID.
  --webhook-secret VALUE         Optional webhook secret. Env fallback: CLICKUP_WEBHOOK_SECRET.
  --install-method uv|pip|pipx|skip
  --cursor project|global|skip
  --skill                        Install the bundled Codex skill after setup.
  --yes                          Use default non-secret choices.
  -h, --help                     Show this help.
TXT
}

require_value() {
  local option="$1"
  local value="${2:-}"
  if [[ -z "${value}" ]]; then
    printf '%s requires a value.\n' "${option}" >&2
    exit 2
  fi
  printf '%s' "${value}"
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --non-interactive)
        NON_INTERACTIVE="true"
        shift
        ;;
      --api-key)
        API_KEY="$(require_value "$1" "${2:-}")"
        shift 2
        ;;
      --workspace-id)
        WORKSPACE_ID="$(require_value "$1" "${2:-}")"
        shift 2
        ;;
      --webhook-secret)
        WEBHOOK_SECRET="$(require_value "$1" "${2:-}")"
        shift 2
        ;;
      --install-method)
        INSTALL_METHOD="$(require_value "$1" "${2:-}")"
        shift 2
        ;;
      --cursor)
        CURSOR_SCOPE="$(require_value "$1" "${2:-}")"
        shift 2
        ;;
      --skill)
        INSTALL_SKILL="true"
        shift
        ;;
      --yes)
        YES="true"
        shift
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        printf 'Unknown option: %s\n' "$1" >&2
        usage >&2
        exit 2
        ;;
    esac
  done

  case "${INSTALL_METHOD}" in
    prompt|uv|pip|pipx|skip) ;;
    *)
      printf 'Unsupported --install-method: %s\n' "${INSTALL_METHOD}" >&2
      exit 2
      ;;
  esac
  case "${CURSOR_SCOPE}" in
    prompt|project|global|skip) ;;
    *)
      printf 'Unsupported --cursor scope: %s\n' "${CURSOR_SCOPE}" >&2
      exit 2
      ;;
  esac
  if [[ "${YES}" == "true" && "${INSTALL_METHOD}" == "prompt" ]]; then
    INSTALL_METHOD="uv"
  fi
  if [[ "${YES}" == "true" && "${CURSOR_SCOPE}" == "prompt" ]]; then
    CURSOR_SCOPE="project"
  fi
}

write_env_file() {
  local env_file="$1"
  local api_key="$2"
  local workspace_id="$3"
  local webhook_secret="$4"

  if [[ -e "${env_file}" ]]; then
    local backup="${env_file}.bak.$(date +%Y%m%d%H%M%S)"
    cp "${env_file}" "${backup}"
    chmod 600 "${backup}"
    say "Existing env file backed up to ${backup}"
  fi

  umask 077
  {
    printf '# Local clickup-agent secrets. Generated by scripts/install.sh.\n'
    printf '# Do not commit this file.\n'
    printf 'CLICKUP_API_KEY=%s\n' "$(shell_quote_env_value "${api_key}")"
    printf 'CLICKUP_WORKSPACE_ID=%s\n' "$(shell_quote_env_value "${workspace_id}")"
    printf 'CLICKUP_WEBHOOK_SECRET=%s\n' "$(shell_quote_env_value "${webhook_secret}")"
  } > "${env_file}"
  chmod 600 "${env_file}"
}

install_package_method() {
  local method="$1"
  case "${method}" in
    uv)
      if ! command -v uv >/dev/null 2>&1; then
        say "uv is not installed. Skipping package install."
        printf 'Install uv later, then run: uv tool install "%s" --python 3.12 --reinstall\n' "${REPO_ROOT}"
        return 0
      fi
      (cd "${REPO_ROOT}" && uv tool install . --python 3.12 --reinstall)
      ;;
    pip)
      (cd "${REPO_ROOT}" && python3 -m pip install -e .)
      ;;
    pipx)
      if ! command -v pipx >/dev/null 2>&1; then
        say "pipx is not installed. Skipping package install."
        printf 'Install pipx later, then run: pipx install "%s"\n' "${REPO_ROOT}"
        return 0
      fi
      (cd "${REPO_ROOT}" && pipx install . --force)
      ;;
    skip)
      say "Skipping package install."
      ;;
  esac
}

install_package() {
  if [[ "${INSTALL_METHOD}" != "prompt" ]]; then
    install_package_method "${INSTALL_METHOD}"
    return 0
  fi

  say "Install the clickup-agent command?"
  printf '  1) uv tool install . (recommended when uv is available)\n'
  printf '  2) python -m pip install -e . (editable development install)\n'
  printf '  3) pipx install .\n'
  printf '  4) skip for now\n'

  local choice
  read -r -p "Choose 1, 2, 3, or 4 [1]: " choice
  choice="${choice:-1}"

  case "${choice}" in
    1)
      install_package_method "uv"
      ;;
    2)
      install_package_method "pip"
      ;;
    3)
      install_package_method "pipx"
      ;;
    4)
      install_package_method "skip"
      ;;
    *)
      say "Unknown choice; skipping package install."
      ;;
  esac
}

cursor_config_path() {
  local scope="$1"
  case "${scope}" in
    project)
      printf '%s/.cursor/mcp.json' "${REPO_ROOT}"
      ;;
    global)
      printf '%s/.cursor/mcp.json' "${HOME}"
      ;;
  esac
}

install_cursor_config() {
  local scope="$1"
  local config_file

  config_file="$(cursor_config_path "${scope}")"

  mkdir -p "$(dirname "${config_file}")"
  if [[ -e "${config_file}" ]]; then
    local backup="${config_file}.bak.$(date +%Y%m%d%H%M%S)"
    cp "${config_file}" "${backup}"
    say "Existing Cursor MCP config backed up to ${backup}"
  fi

  python3 - "${config_file}" <<'PY'
import json
import sys
from pathlib import Path

config_path = Path(sys.argv[1])

if config_path.exists() and config_path.read_text(encoding="utf-8").strip():
    try:
        config = json.loads(config_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise SystemExit(f"Could not parse existing {config_path}: {exc}") from exc
else:
    config = {}

servers = config.setdefault("mcpServers", {})
servers["clickup-agent"] = {
    "command": "clickup-agent",
    "args": ["mcp"],
    "env": {},
}

config_path.write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")
PY

  say "Installed Cursor MCP server config at ${config_file}"
}

maybe_install_cursor_config() {
  say "Install clickup-agent for Cursor MCP access?"
  printf '  1) project config at .cursor/mcp.json\n'
  printf '  2) global config at ~/.cursor/mcp.json\n'
  printf '  3) skip for now\n'

  local choice
  read -r -p "Choose 1, 2, or 3 [1]: " choice
  choice="${choice:-1}"

  case "${choice}" in
    1)
      install_cursor_config "project"
      ;;
    2)
      install_cursor_config "global"
      ;;
    3)
      say "Skipping Cursor MCP config."
      ;;
    *)
      say "Unknown choice; skipping Cursor MCP config."
      ;;
  esac
}

print_llm_client_snippet() {
  say "LLM client MCP-style configuration"
  cat <<JSON
{
  "mcpServers": {
    "clickup-agent": {
      "command": "clickup-agent",
      "args": ["mcp"],
      "env": {}
    }
  }
}
JSON
}

main() {
  parse_args "$@"

  say "clickup-agent local installer"
  printf 'This will create the one native clickup-agent env file: %s\n' "${DEFAULT_ENV_FILE}"

  local env_file
  env_file="${DEFAULT_ENV_FILE}"

  local api_key
  api_key="${API_KEY}"
  if [[ -z "${api_key}" ]]; then
    if [[ "${NON_INTERACTIVE}" == "true" ]]; then
      printf 'CLICKUP_API_KEY is required. Pass --api-key or set CLICKUP_API_KEY.\n' >&2
      exit 2
    fi
    api_key="$(prompt_secret "Paste your ClickUp API token" "true")"
  fi

  local workspace_id
  workspace_id="${WORKSPACE_ID}"
  if [[ -z "${workspace_id}" && "${NON_INTERACTIVE}" != "true" ]]; then
    workspace_id="$(prompt_visible "Default ClickUp workspace ID (optional)")"
  fi

  local webhook_secret
  webhook_secret="${WEBHOOK_SECRET}"
  if [[ -z "${webhook_secret}" && "${NON_INTERACTIVE}" != "true" ]]; then
    webhook_secret="$(prompt_secret "Webhook/signing secret for inbound ClickUp events (optional)")"
  fi

  install_package

  mkdir -p "$(dirname "${env_file}")"
  if command -v clickup-agent >/dev/null 2>&1; then
    CLICKUP_API_KEY="${api_key}" \
      CLICKUP_WORKSPACE_ID="${workspace_id}" \
      CLICKUP_WEBHOOK_SECRET="${webhook_secret}" \
      clickup-agent setup --non-interactive --force
  else
    write_env_file "${env_file}" "${api_key}" "${workspace_id}" "${webhook_secret}"
    say "Wrote ${env_file} with owner-only permissions."
  fi

  case "${CURSOR_SCOPE}" in
    prompt)
      maybe_install_cursor_config
      ;;
    project|global)
      install_cursor_config "${CURSOR_SCOPE}"
      ;;
    skip)
      say "Skipping Cursor MCP config."
      ;;
  esac

  if [[ "${INSTALL_SKILL}" == "true" ]]; then
    bash "${SCRIPT_DIR}/install-skill.sh"
  fi

  print_llm_client_snippet

  say "Next check:"
  printf 'clickup-agent connect <cursor|claude-code|codex|generic>\n'
  printf 'clickup-agent doctor --live-auth\n'
}

main "$@"
