#!/usr/bin/env bash
# Interactive local installer for clickup-agent.
#
# This script intentionally writes secrets only to a gitignored env file with
# owner-only permissions. It does not send the token anywhere or commit it.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
DEFAULT_ENV_FILE="${REPO_ROOT}/.env.local"

say() {
  printf '\n%s\n' "$*"
}

prompt_visible() {
  local prompt="$1"
  local default_value="${2:-}"
  local value

  if [[ -n "${default_value}" ]]; then
    read -r -p "${prompt} [${default_value}]: " value
    printf '%s' "${value:-$default_value}"
  else
    read -r -p "${prompt}: " value
    printf '%s' "${value}"
  fi
}

prompt_secret() {
  local prompt="$1"
  local required="${2:-false}"
  local value=""

  while true; do
    read -r -s -p "${prompt}: " value
    printf '\n' >&2
    if [[ -n "${value}" || "${required}" != "true" ]]; then
      printf '%s' "${value}"
      return 0
    fi
    printf 'This value is required.\n' >&2
  done
}

shell_quote_env_value() {
  local value="$1"
  value="${value//$'\r'/}"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '"%s"' "${value}"
}

write_env_file() {
  local env_file="$1"
  local api_key="$2"
  local workspace_id="$3"
  local webhook_secret="$4"

  if [[ -e "${env_file}" ]]; then
    local backup="${env_file}.bak.$(date +%Y%m%d%H%M%S)"
    cp "${env_file}" "${backup}"
    chmod 600 "${backup}"
    say "Existing env file backed up to ${backup}"
  fi

  umask 077
  {
    printf '# Local clickup-agent secrets. Generated by scripts/install.sh.\n'
    printf '# Do not commit this file.\n'
    printf 'CLICKUP_API_KEY=%s\n' "$(shell_quote_env_value "${api_key}")"
    printf 'CLICKUP_WORKSPACE_ID=%s\n' "$(shell_quote_env_value "${workspace_id}")"
    printf 'CLICKUP_WEBHOOK_SECRET=%s\n' "$(shell_quote_env_value "${webhook_secret}")"
  } > "${env_file}"
  chmod 600 "${env_file}"
}

install_package() {
  say "Install the clickup-agent command?"
  printf '  1) uv tool install . (recommended when uv is available)\n'
  printf '  2) python -m pip install -e . (editable development install)\n'
  printf '  3) pipx install .\n'
  printf '  4) skip for now\n'

  local choice
  read -r -p "Choose 1, 2, 3, or 4 [1]: " choice
  choice="${choice:-1}"

  case "${choice}" in
    1)
      if ! command -v uv >/dev/null 2>&1; then
        say "uv is not installed. Skipping package install."
        printf 'Install uv later, then run: uv tool install "%s" --python 3.12 --reinstall\n' "${REPO_ROOT}"
        return 0
      fi
      (cd "${REPO_ROOT}" && uv tool install . --python 3.12 --reinstall)
      ;;
    2)
      (cd "${REPO_ROOT}" && python3 -m pip install -e .)
      ;;
    3)
      if ! command -v pipx >/dev/null 2>&1; then
        say "pipx is not installed. Skipping package install."
        printf 'Install pipx later, then run: pipx install "%s"\n' "${REPO_ROOT}"
        return 0
      fi
      (cd "${REPO_ROOT}" && pipx install . --force)
      ;;
    4)
      say "Skipping package install."
      ;;
    *)
      say "Unknown choice; skipping package install."
      ;;
  esac
}

cursor_config_path() {
  local scope="$1"
  case "${scope}" in
    project)
      printf '%s/.cursor/mcp.json' "${REPO_ROOT}"
      ;;
    global)
      printf '%s/.cursor/mcp.json' "${HOME}"
      ;;
  esac
}

install_cursor_config() {
  local env_file="$1"
  local scope="$2"
  local config_file
  local command_path

  config_file="$(cursor_config_path "${scope}")"
  command_path="$(command -v clickup-agent || true)"
  command_path="${command_path:-clickup-agent}"

  mkdir -p "$(dirname "${config_file}")"
  if [[ -e "${config_file}" ]]; then
    local backup="${config_file}.bak.$(date +%Y%m%d%H%M%S)"
    cp "${config_file}" "${backup}"
    say "Existing Cursor MCP config backed up to ${backup}"
  fi

  python3 - "${config_file}" "${command_path}" "${env_file}" <<'PY'
import json
import sys
from pathlib import Path

config_path = Path(sys.argv[1])
command = sys.argv[2]
env_file = sys.argv[3]

if config_path.exists() and config_path.read_text(encoding="utf-8").strip():
    try:
        config = json.loads(config_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise SystemExit(f"Could not parse existing {config_path}: {exc}") from exc
else:
    config = {}

servers = config.setdefault("mcpServers", {})
servers["clickup-agent"] = {
    "command": command,
    "args": ["mcp"],
    "env": {
        "CLICKUP_ENV_FILE": env_file,
    },
}

config_path.write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")
PY

  say "Installed Cursor MCP server config at ${config_file}"
}

maybe_install_cursor_config() {
  local env_file="$1"

  say "Install clickup-agent for Cursor MCP access?"
  printf '  1) project config at .cursor/mcp.json\n'
  printf '  2) global config at ~/.cursor/mcp.json\n'
  printf '  3) skip for now\n'

  local choice
  read -r -p "Choose 1, 2, or 3 [1]: " choice
  choice="${choice:-1}"

  case "${choice}" in
    1)
      install_cursor_config "${env_file}" "project"
      ;;
    2)
      install_cursor_config "${env_file}" "global"
      ;;
    3)
      say "Skipping Cursor MCP config."
      ;;
    *)
      say "Unknown choice; skipping Cursor MCP config."
      ;;
  esac
}

print_llm_client_snippet() {
  local env_file="$1"

  say "LLM client MCP-style configuration"
  cat <<JSON
{
  "mcpServers": {
    "clickup-agent": {
      "command": "clickup-agent",
      "args": ["mcp"],
      "env": {
        "CLICKUP_ENV_FILE": "${env_file}"
      }
    }
  }
}
JSON
}

main() {
  say "clickup-agent local installer"
  printf 'This will create a gitignored env file for your ClickUp credentials.\n'

  local env_file
  env_file="$(prompt_visible "Env file path" "${DEFAULT_ENV_FILE}")"

  local api_key
  api_key="$(prompt_secret "Paste your ClickUp API token" "true")"

  local workspace_id
  workspace_id="$(prompt_visible "Default ClickUp workspace ID (optional)")"

  local webhook_secret
  webhook_secret="$(prompt_secret "Webhook/signing secret for inbound ClickUp events (optional)")"

  mkdir -p "$(dirname "${env_file}")"
  write_env_file "${env_file}" "${api_key}" "${workspace_id}" "${webhook_secret}"
  say "Wrote ${env_file} with owner-only permissions."

  install_package
  maybe_install_cursor_config "${env_file}"
  print_llm_client_snippet "${env_file}"

  say "Next check:"
  printf 'clickup-agent doctor --env-file "%s"\n' "${env_file}"
}

main "$@"
